# Análisis de Base de Datos

## Pandas

```{admonition} ¿Qué es Pandas?
<div align="justify"><strong>Pandas</strong> es una muy popular librería de código abierto dentro de los desarrolladores de Python, y sobre todo dentro del ámbito de Data Science y Machine Learning, ya que ofrece unas estructuras muy poderosas y flexibles que facilitan la manipulación y tratamiento de datos. Las dos estructuras de datos principales dentro del paquete Pandas son:</div>

-  <div align="justify"><strong>Series</strong>: array unidimensional etiquetado capaz de almacenar cualquier tipo de dato.</div> 

-  <div align="justify"><strong>DataFrame</strong>: estructura bidimensional con columnas que pueden ser también de cualquier tipo. Estas columnas son a su vez Series.</div>
```

```{dropdown} Revisa para profundizar

[Documentación de Pandas](https://pandas.pydata.org/docs/user_guide/index.html)

[Atributos, operaciones y funciones en Series](https://pandas.pydata.org/pandas-docs/stable/reference/series.html)
```

In [1]:
 # en caso de que no estar instalada: pip install pandas

In [2]:
# importamos las librerías, le damos un seudónimo a las librerias para mejorar 
# legibilidad en el código.
import pandas as pd

<div align="justify"><strong>Crear un DataFrame.</strong>: Crea un DataFrame simple a partir de un diccionario </div> 

In [3]:
data = {'Nombre': ['Juan', 'María', 'Carlos', 'Luis'],
        'Edad': [25, 30, 35, 40],
        'Ciudad': ['México', 'Madrid', 'Buenos Aires', 'Lima']}
df = pd.DataFrame(data)
print(df)

   Nombre  Edad        Ciudad
0    Juan    25        México
1   María    30        Madrid
2  Carlos    35  Buenos Aires
3    Luis    40          Lima


<div align="justify"><strong>Seleccionar columnas</strong> : Selecciona una columna específica del DataFrame.</div>  

In [4]:
print(df['Nombre'])

0      Juan
1     María
2    Carlos
3      Luis
Name: Nombre, dtype: object


<div align="justify"><strong>Filtrar filas</strong>: Filtra filas basadas en una condición.</div> 

In [5]:
filtro = df['Edad'] > 30
print(df[filtro])

   Nombre  Edad        Ciudad
2  Carlos    35  Buenos Aires
3    Luis    40          Lima


<div align="justify"><strong>Agregar una nueva columna</strong>: Agrega una nueva columna al DataFrame.</div>

In [6]:
df['Género'] = ['Hombre', 'Mujer', 'Hombre', 'Hombre']
print(df)

   Nombre  Edad        Ciudad  Género
0    Juan    25        México  Hombre
1   María    30        Madrid   Mujer
2  Carlos    35  Buenos Aires  Hombre
3    Luis    40          Lima  Hombre


<div align="justify"><strong> Eliminar columnas</strong> : Elimina una columna del DataFrame.</div> 

In [7]:
df = df.drop('Ciudad', axis=1)
print(df)

   Nombre  Edad  Género
0    Juan    25  Hombre
1   María    30   Mujer
2  Carlos    35  Hombre
3    Luis    40  Hombre


<div align="justify"><strong> Agregar una fila</strong>: Agrega una nueva fila al DataFrame.</div> 

In [8]:
nueva_fila = pd.DataFrame({'Nombre': ['Laura'], 'Edad': [28], 'Ciudad': ['Barcelona'],
                           'Género': ['Mujer']})
df = pd.concat([df, nueva_fila], ignore_index=True)
print(df)

   Nombre  Edad  Género     Ciudad
0    Juan    25  Hombre        NaN
1   María    30   Mujer        NaN
2  Carlos    35  Hombre        NaN
3    Luis    40  Hombre        NaN
4   Laura    28   Mujer  Barcelona


<div align="justify"><strong> Eliminar filas</strong>: Elimina filas del DataFrame.</div>  

In [9]:
df = df.drop(0)
print(df)

   Nombre  Edad  Género     Ciudad
1   María    30   Mujer        NaN
2  Carlos    35  Hombre        NaN
3    Luis    40  Hombre        NaN
4   Laura    28   Mujer  Barcelona


<div align="justify"><strong>Exportar a CSV</strong> : Exporta el DataFrame a un archivo CSV.</div>

In [10]:
df.to_csv('nuevo_archivo.csv', index=False)

## Numpy

<div align="justify"><strong>Numpy</strong> es una librería de Python especializada en el cálculo numérico y el análisis de datos, especialmente para un gran volumen de datos.Incorpora una nueva clase de objetos llamados arrays que permite representar colecciones de datos de un mismo tipo en varias dimensiones, y funciones muy eficientes para su manipulación.</div> 

<div align="justify">Para crear un array se utiliza la siguiente función de NumPy</div>


- <div align="justify"><strong>np.array(lista):</strong> Crea un array a partir de la lista o tupla lista y devuelve una referencia a él. El número de dimensiones del array dependerá de las listas o tuplas anidadas en lista:</div>  
- <div align="justify">Para una lista de valores se crea un array de una dimensión, también conocido como vector.</div> 
- <div align="justify">Para una lista de listas de valores se crea un array de dos dimensiones, también conocido como matriz.</div>
- <div align="justify">Para una lista de listas de listas de valores se crea un array de tres dimensiones, también conocido como cubo.</div>
- <div align="justify">Y así sucesivamente. No hay límite en el número de dimensiones del array más allá de la memoria disponible en el sistema.</div> 



```{dropdown} Revisa información para profundizar
[Profundiza  en su documentación](https://numpy.org)
```

In [11]:
import numpy as np

# Crear un array NumPy unidimensional
array_unidimensional = np.array([1, 2, 3, 4, 5])
print("Array unidimensional:")
print(array_unidimensional)

# Crear un array NumPy bidimensional (matriz)
array_bidimensional = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\nArray bidimensional:")
print(array_bidimensional)


Array unidimensional:
[1 2 3 4 5]

Array bidimensional:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
import numpy as np

# Crear dos arrays NumPy
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Suma de arrays
suma = array1 + array2
print("Suma de arrays:")
print(suma)

# Producto de arrays
producto = array1 * array2
print("\nProducto de arrays:")
print(producto)

# Operaciones matemáticas
cuadrado = np.square(array1)
print("\nCuadrado de array1:")
print(cuadrado)


Suma de arrays:
[5 7 9]

Producto de arrays:
[ 4 10 18]

Cuadrado de array1:
[1 4 9]


In [13]:
import numpy as np

# Generar datos aleatorios
datos_aleatorios = np.random.rand(5)  # Array unidimensional de 5 números aleatorios entre 0 y 1
print("Datos aleatorios:")
print(datos_aleatorios)

# Generar matriz de números aleatorios
matriz_aleatoria = np.random.randint(1, 10, size=(3, 3))  # Matriz 3x3 de números aleatorios entre 1 y 9
print("\nMatriz aleatoria:")
print(matriz_aleatoria)


Datos aleatorios:
[0.50577152 0.81882292 0.95580129 0.69493095 0.55027507]

Matriz aleatoria:
[[8 5 8]
 [1 7 6]
 [4 7 3]]


In [14]:
import numpy as np

# Crear un array NumPy
mi_array = np.array([1, 2, 3, 4, 5])

# Acceder a un elemento específico
print("Primer elemento:", mi_array[0])

# Acceder a un rango de elementos
print("Primeros tres elementos:", mi_array[:3])

# Modificar un elemento
mi_array[2] = 10
print("Array modificado:", mi_array)


Primer elemento: 1
Primeros tres elementos: [1 2 3]
Array modificado: [ 1  2 10  4  5]
